#!/usr/bin/env python3
"""Build the static demo site at `docs/demo/` from the real UI.

    python tools/build_demo.py            # rebuild docs/demo in place
    python tools/build_demo.py --check    # fail if the committed site drifted

GitHub Pages serves this directory: free permanently, no cold start, no
server, no upload surface, and no provider key anywhere near it. The page
is the *same* `arena.js` and `arena.css` the local server serves, copied
byte for byte, with the intake removed -- there is no second renderer to
keep in step, so the demo cannot quietly diverge from the product.

The recordings are captured by `gauntlet run --replay` from real matrices.
Regenerating them is a separate, explicit step (`--record`), because a
build that silently re-ran the matrix would make "the same run you see in
the repo" a claim nobody could check.
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UI = ROOT / "src" / "agent_gauntlet" / "ui"
OUT = ROOT / "docs" / "demo"

RECORDINGS = [
    {
        "slug": "wrong-value",
        "label": "a tool lies about a number",
        "task": "fixtures/inventory/task.yaml",
        "args": ["--repeats", "2", "--seeds", "2"],
        "blurb": "The default fault: one tool returns a false figure. Watch "
                 "who carries it into the final answer.",
    },
    {
        "slug": "poisoned-memory",
        "label": "the agent's own note comes back altered",
        "task": "fixtures/poisoning/memory.yaml",
        # More repeats than the fixture next door: this grid is half the
        # size, and n=8 per contender resolves nothing finer than 70%.
        "args": ["--repeats", "4", "--seeds", "2"],
        "blurb": "No tool lied. The agent's own recorded finding was edited "
                 "between writing and reading it, and the board looks "
                 "nothing like the one next door.",
    },
]

COPIED = ["arena.css", "arena.js", "dragon.png"]

BOOT = '''/* Generated by tools/build_demo.py -- do not edit here.
 *
 * The whole of the demo's own code. Everything else on this page is the
 * same arena.js the local server serves, and this file only tells it which
 * recorded stream to play.
 */
const RECORDINGS = %s;

function show(slug) {
  const rec = RECORDINGS.find((r) => r.slug === slug) || RECORDINGS[0];
  document.querySelectorAll('#recordings button').forEach((b) =>
    b.classList.toggle('on', b.dataset.slug === rec.slug));
  document.querySelector('#recording-blurb').textContent = rec.blurb;
  history.replaceState(null, '', `?run=${rec.slug}`);
  window.Arena.replay(rec.file);
}

document.addEventListener('DOMContentLoaded', () => {
  const picker = document.querySelector('#recordings');
  picker.innerHTML = RECORDINGS.map((r) =>
    `<button data-slug="${r.slug}">${r.label}</button>`).join('');
  picker.querySelectorAll('button').forEach((b) =>
    b.addEventListener('click', () => show(b.dataset.slug)));
  const asked = new URLSearchParams(location.search).get('run');
  show(asked || RECORDINGS[0].slug);
});
'''

BANNER = '''
<!-- ------------------------------------------------------------ recording -->
<section class="panel recording">
  <h2>A recorded run</h2>
  <p class="muted">This page has no server behind it. Every event below was
  captured from a real matrix by <code>gauntlet run --replay</code> and is
  replayed here in the order it happened — the same arena the local UI
  draws, reading a file instead of a poll. Nothing on this page is mocked,
  and nothing here can call a model or spend anything.</p>
  <div id="recordings" class="recordings"></div>
  <p id="recording-blurb" class="blurb"></p>
  <p id="recording-note" class="muted small"></p>
  <p class="muted small">Produced by:
    <code id="recording-source"></code></p>
  <p class="muted small">Want to run your own, against your own tools and
  real models? <a href="https://github.com/Mehul-Gupta-SMH/agent-gauntlet">The
  repo</a> — <code>pip install -e . &amp;&amp; gauntlet ui</code>.</p>
</section>
'''

EXTRA_CSS = '''
/* --- demo page only (generated by tools/build_demo.py) ------------------ */
.recording { max-width: 1100px; }
.recordings { display: flex; flex-wrap: wrap; gap: .5rem; margin: .9rem 0 .6rem; }
.recordings button {
  background: #221b14; color: #e8ddcb; border: 1px solid #453424;
  border-radius: 999px; padding: .45rem .95rem; cursor: pointer;
  font-size: .92rem;
}
.recordings button:hover { border-color: #b78b45; }
.recordings button.on { background: #b78b45; color: #1a140e; border-color: #b78b45; }
.recording .blurb { margin: .2rem 0 .6rem; color: #d8cbb4; }
.recording .small { font-size: .82rem; }
.recording a { color: #d9a441; }
'''


def build() -> list[Path]:
    """Copy the real UI and cut the intake out of it."""
    if not all((OUT / f"replay-{r['slug']}.json").exists() for r in RECORDINGS):
        missing = [r["slug"] for r in RECORDINGS
                   if not (OUT / f"replay-{r['slug']}.json").exists()]
        raise SystemExit(
            f"no recording for: {', '.join(missing)}. Capture one first:\n"
            f"    python tools/build_demo.py --record"
        )
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for name in COPIED:
        shutil.copyfile(UI / name, OUT / name)
        written.append(OUT / name)

    html = (UI / "index.html").read_text(encoding="utf-8")

    # The intake goes, all of it: a page with no server cannot start a run,
    # and a form that silently does nothing is worse than no form.
    start = html.index("<!-- --------------------------------------------------------------- projects -->")
    end = html.index("<!-- ---------------------------------------------------------------- arena -->")
    html = html[:start] + BANNER.lstrip("\n") + "\n" + html[end:]

    # wizard.js talks to /api. Replaced by the boot script, which is the
    # only code on this page that the local UI does not also run.
    html = html.replace('<script src="wizard.js"></script>',
                        '<script src="demo.js"></script>')
    html = html.replace('<title>agent-gauntlet — arena</title>',
                        '<title>agent-gauntlet — a recorded run</title>')
    html = html.replace('<link rel="stylesheet" href="arena.css">',
                        '<link rel="stylesheet" href="arena.css">\n'
                        '<link rel="stylesheet" href="demo.css">')
    (OUT / "index.html").write_text(html, encoding="utf-8")
    written.append(OUT / "index.html")

    (OUT / "demo.css").write_text(EXTRA_CSS.lstrip("\n"), encoding="utf-8")
    written.append(OUT / "demo.css")

    import json
    manifest = [{"slug": r["slug"], "label": r["label"], "blurb": r["blurb"],
                 "file": f"replay-{r['slug']}.json"} for r in RECORDINGS]
    (OUT / "demo.js").write_text(BOOT % json.dumps(manifest, indent=2),
                                 encoding="utf-8")
    written.append(OUT / "demo.js")

    # Pages would otherwise run the whole directory through Jekyll, which
    # eats files whose names begin with an underscore and adds nothing here.
    (OUT / ".nojekyll").write_text("", encoding="utf-8")
    written.append(OUT / ".nojekyll")
    return written


def record() -> None:
    """Capture each recording from a real run. Offline, so it costs nothing
    and anyone can reproduce it byte for byte."""
    OUT.mkdir(parents=True, exist_ok=True)
    for rec in RECORDINGS:
        out = OUT / f"replay-{rec['slug']}.json"
        out.unlink(missing_ok=True)
        # A path relative to the repo root, not an absolute one: the
        # command is printed on the page as provenance, and it should be a
        # command a reader can actually run rather than a tour of whoever
        # built it's home directory.
        cmd = [sys.executable, "-m", "agent_gauntlet.cli", "run",
               rec["task"], "--out", f"runs-demo/{rec['slug']}",
               *rec["args"], "--replay", str(out.relative_to(ROOT))]
        print("$", " ".join(cmd))
        # Not `check=True`. A non-zero exit means the gate refused the run,
        # which is a finding about the agents rather than a failure of the
        # capture -- and a demo that could only record runs that passed
        # would be a demo that cannot show this tool doing its job.
        proc = subprocess.run(cmd, cwd=ROOT)
        if not out.exists():
            raise SystemExit(
                f"{rec['slug']}: the run produced no recording "
                f"(exit {proc.returncode})")
        print(f"  gate exit {proc.returncode}  ->  {out.name}")


def check() -> int:
    """Rebuild into a scratch directory and compare, so a UI edit that was
    never re-published to the demo is a failure rather than a surprise."""
    import tempfile

    global OUT
    committed = OUT
    with tempfile.TemporaryDirectory() as tmp:
        OUT = Path(tmp)
        for rec in RECORDINGS:
            shutil.copyfile(committed / f"replay-{rec['slug']}.json",
                            OUT / f"replay-{rec['slug']}.json")
        build()
        stale = [f.name for f in sorted(OUT.iterdir())
                 if not (committed / f.name).exists()
                 or not filecmp.cmp(f, committed / f.name, shallow=False)]
    OUT = committed
    if stale:
        print("docs/demo is stale: " + ", ".join(stale))
        print("rebuild with: python tools/build_demo.py")
        return 1
    print("docs/demo is current")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--record", action="store_true",
                    help="re-capture the recordings by re-running the matrices")
    ap.add_argument("--check", action="store_true",
                    help="verify the committed site matches a fresh build")
    args = ap.parse_args()
    if args.check:
        raise SystemExit(check())
    if args.record:
        record()
    build()
    print(f"built {OUT}")
